FROM node:16.17.1-alpine3.15
WORKDIR /app
COPY ./.prod/entrypoint.backend.sh /
COPY ./environment/prod.backend.env /

STOPSIGNAL SIGKILL
EXPOSE 4243

ENTRYPOINT ["/entrypoint.backend.sh"]
# ENTRYPOINT ["/bin/sh"]