version: "3.3"

services:
  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: .dev/dockerfile.backend
    restart: always
    volumes:
      - ../backend:/app
    networks:
      - net
    ports:
      - 4243:4243

  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: .dev/dockerfile.frontend
    restart: always
    volumes:
      - ../frontend:/app
    networks:
      - net
    ports:
      - 4242:4242

  database:
    container_name: database
    build:
      context: ../
      dockerfile: .dev/dockerfile.database
    restart: always
    volumes:
      - ../database:/database
    networks:
      - net
    ports:
      - 4245:4245
    environment:
      POSTGRES_PASSWORD: "1234" # FIXME 나중에 수정!
      PGPORT: 4245
      PGDATA: '/database'

    tty: true

networks:
  net:
    driver: bridge
