FROM postgres:alpine3.16
COPY ./.dev/entrypoint.database.initdb.sh /docker-entrypoint-initdb.d/
COPY ./.dev/entrypoint.database.sh /

STOPSIGNAL SIGKILL
EXPOSE 4245

USER postgres
ENTRYPOINT ["/entrypoint.database.sh"]