#!/bin/bash
# FIXME env

psql --port 4245 << eof
CREATE DATABASE "User";
CREATE DATABASE "Channel";

CREATE DATABASE "MatchHistory";
CREATE DATABASE "Friend";
CREATE DATABASE "Block";
CREATE DATABASE "InChannel";

CREATE DATABASE "Admin";
CREATE DATABASE "Mute";
CREATE DATABASE "Ban";

CREATE DATABASE "DirectMessage";

ALTER USER postgres WITH PASSWORD '1234';
GRANT ALL PRIVILEGES ON DATABASE postgres TO postgres;
eof
