version: "3.3"

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./.prod/dockerfile.backend
    restart: always
    networks:
      - net
    ports:
      - 4243:4243
    env_file:
      - environment/prod.backend.docker.env

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./.prod/dockerfile.frontend
    restart: always
    networks:
      - net
    ports:
      - 4242:4242

  database:
    container_name: database
    build:
      context: ./
      dockerfile: ./.prod/dockerfile.database
    restart: always
    volumes:
      - ./database:/database
    networks:
      - net
    env_file:
      - environment/prod.database.env

networks:
  net:
    driver: bridge
